[tool.poetry]
name = "shiki-organizer"
version = "0.3.0"
description = "To-do list cli program"
authors = ["Niko Honu <nikohonu@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "shiki_organizer"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
appdirs = "^1.4.4"
termcolor = "^2.0.1"
peewee = "^3.15.3"
pyside6 = "^6.4.0.1"

[tool.poetry.scripts]
so = "shiki_organizer.__main__:main"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
python-lsp-server = "^1.6.0"
python-lsp-black = "^1.2.1"
pyls-isort = "^0.2.2"
pyright = "^1.1.279"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
