[tool.poetry]
name = "shiki-organizer"
version = "0.3.1"
description = "To-do list cli program"
authors = ["Niko Honu <nikohonu@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "shiki_organizer"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
appdirs = "^1.4.4"
peewee = "^3.15.3"
pyside6 = "^6.4.0.1"
termcolor = "^2.1.0"

[tool.poetry.scripts]
shiki-organizer = "shiki_organizer.gui.__main__:main"
so = "shiki_organizer.cli.__main__:main"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
pyright = "^1.1.279"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
